### ISSUE TITLE
How to check if an object exists?

### ISSUE THREAD

**Issue by Ser5** [psecio/gatekeeper#22]
One can use something like `Gatekeeper::findGroupById(1)` to get a group. I thought that this method, if it can't find the record, returns null - I doubt that not finding the record is an exceptional case - but it does throw an exception.

Am I right that there is no way to check if object exists in a clean way? Like:

```
if (is_null(Gatekeeper::findGroupByName('group_name'))) {
   Gatekeeper::createGroup($attrs);
}
```

Do we have to deal with exceptions every time for this? If it is so, I think it's not a right way.

**Comment by enygma** [comment]
yeah, that's a good point....I'm thinking that more and more it should just return `false` when the item isn't found. Initially I was using exceptions for handling all of the "errors" in the tool but I think a better mix is definitely a better idea. I'm not sure if `null` or `false` is a better option here though.

**Comment by Ser5** [comment]
I'm used to idea that functions that usually returns strings, numbers, arrays etc should return `false` when the data not found. But functions that return objects should return `null` - like in "serious" OOP languages like C#, Java and such. But it causes a bit of mess - I never remember which method returns `false` and which returns `null`, so if Gatekeeper will return `false` - I'm happy. Moreover, in PHP `false` is easier to handle, `null` requires awkward approach with using special methods like `is_null()` and `empty()`.

**Comment by enygma** [comment]
The "find by" operations now return `false` instead of throwing an exception in cb527fe. Thanks for the recommendation!
