### ISSUE TITLE
Installation and configuration

### ISSUE THREAD

**Issue by Ser5** [psecio/gatekeeper#24]
Here is the page:
http://gatekeeper-auth.readthedocs.org/en/latest/installation-and-configuration/

_"Create a database named gatekeeper and create a user for it (this is configured later)"_
I'm not sure that users wish to create one more database for storing users... I think they'll try to use existing database. This interferes with issue #6, which seems to suppose same idea... I'm not quite sure if creating different database should be mentioned in the manual.

_"Open both of these files and update the connection information to match the database you created earlier."_
This is not enough. A developer also needs to change paths.migrations to the actual directory, relative to the directory we run phinx from.

``` php
<?php
require_once 'vendor/autoload.php';
Gatekeeper::init();
?>
```

This short example gives an error, as one should use not just `Gatekeeper`, but `\Psecio\Gatekeeper\Gatekeeper`.

**Comment by enygma** [comment]
Good point - I'm actually in the process of working up a bash script to help make installation even easier and making these changes for the user without the manual editing/copying of the files.

**Comment by enygma** [comment]
So there's now a `bin/setup.sh` script that can be executed to set up the Gatekeeper system. It still requires the user to create the database first but at least it automates the rest. Going to close this issue out.
