### ISSUE TITLE
Adding groups on user creation doesn't seem to work

### ISSUE THREAD

**Issue by Ser5** [psecio/gatekeeper#26]
If I use following code:

``` php
$gkUserData = array(
    'username'      => $userData['email_address'],
    'password'      => '111111',
    'email'         => $userData['email_address'],
    'first_name'    => $userData['first_name'],
    'last_name'     => $userData['last_name'],
    'groups'        => array($groupId),
);
Gatekeeper::register($gkUserData);
//Gatekeeper::findUserByUsername($userData['email_address'])->addGroup($groupId);
foreach (Gatekeeper::findUserByUsername($userData['email_address'])->groups as $group) {
    var_dump($group->name);
}
```

`var_dump()` vardumps me nothing.
If I uncomment the line with `addGroup()` method, `var_dump()` gives me right results.

Also please note that `Gatekeeper::register()` doesn't return the id of newly created user, so instead of `Gatekeeper::findUserById($userId)` I have to use somewhat inconvenient `Gatekeeper::findUserByUsername($userData['email_address'])`

Note 2:
http://gatekeeper-auth.readthedocs.org/en/latest/users/#creating-users

``` php
// Use can use permission names
$credentials['groups'] = array('group1', 'group2');
```

should be changed to

``` php
// Use can use group names
$credentials['groups'] = array('group1', 'group2');
```

**Comment by enygma** [comment]
`register` now returns the model on success, `false` on failure in 85023c3.
As far as the `groups` and `permissions` creation on the user registration, I'm honestly not sure where that part in the docs came from. I don't see functionality that was designed to handle that.

**Comment by enygma** [comment]
The functionality to add these was added in release 2.6.1. Closing this issue.
