### ISSUE TITLE
How to change a password?

### ISSUE THREAD

**Issue by Ser5** [psecio/gatekeeper#27]
This code gives me false as the result:

``` php
use \Psecio\Gatekeeper\Gatekeeper;
Gatekeeper::disableThrottle();

$user = Gatekeeper::findUserById(1);
$password = 'aaaaaa';
$user->password = $password;
$user->save();
$result = Gatekeeper::authenticate(array('username' => $user->username, 'password' => $password));
var_dump($user->id, $result);
```

**Comment by Ser5** [comment]
Well, I have found that I can save a model by calling

``` php
Gatekeeper::getDatasource()->save($user);
```

But not sure if this a kind of hack or the right way to work.
The documentation doesn't mention any `save()` methods.

**Comment by enygma** [comment]
Yeah, this data source separation was done because there were issues with serializing a model with a PDO connection embedded in it. Seems like the save method could be overridden on the models to get the current data source and mimic the `save()` call directly on the model though.

**Comment by enygma** [comment]
An update in 685a9c116 makes it so that you can call `save` directly on the model instance and have it work as expected.
