### ISSUE TITLE
How to log user out?

### ISSUE THREAD

**Issue by Ser5** [psecio/gatekeeper#28]
http://gatekeeper-auth.readthedocs.org/en/latest/authentication/
Here I can read how to log user in - but how to log user out? I mean, when an user presses "Log out" button - what code should be called?

**Comment by enygma** [comment]
So the only long term session handling Gatekeeper has is the Remember Me cookie that corresponds to the user's details. Other than that, it doesn't maintain a session for you. That's outside the authentication/authorization realm.

That being said, there _does_ need to be a way to destroy that cookie added.

**Comment by enygma** [comment]
It's tough because the "remember me" cookie is technically a session kind of thing but it's not really. I've seen sites that remove the cookie on logout and some that leave it, just terminating the current user's session.

Since Gatekeeper doesn't really do session management I'm not sure managing that cookie is needed either...thoughts?

**Comment by Ser5** [comment]
I think pretty straightforward: if Gatekeeper can register users, restore forgotten passwords, handle throttling, handle security questions, and even authenticate and remember users - why can't it log out users?

In fact I never fully understood what authentication/authorization is, although I read about them several times. So for myself I decided that these are words to make life harder. I prefer to think in simple and practical actions of "check login and password", "log in", "remember", "log out", "get current user".

For me,
`Gatekeeper::authenticate()` is "check login and password";
`Gatekeeper::authenticate($c, true)` is "log in" + "remember";
`Gatekeeper::rememberMe()` is "log in manually" + "remember";
`Gatekeeper::checkRememberMe()` is "get current user".

And, looking at this, I naturally think: "Hey, there is some missing functionality! Where is logging out - twin brother for logging in? And where is logging in for current session only, without remembering?"

If there will be no log out, then what developers should do? Manually delete cookies with `setcookie()`, delete corresponding record from `$_COOKIE` with `unset()`, and remove row from `auth_tokens` with SQL-queries - all of which requires knowledge of Gatekeeper innards? I think it is a kind of hacky way, breaking incapsulation, and forcing to reinvent a wheel. And if Gatekeeper logic changes in the future - all reinvented wheels will break.

Also I think there should be a method that deletes all obsolete records from `auth_tokens` - otherwise there will be a lot of garbage after prolonged usage. One can call that method from cron, for example... or maybe there is a more convenient way.

**Comment by enygma** [comment]
Well, that's the tricky part...technically session management is something different than authentication (proving someone is who they say they are) and authentication (ensuring they have access to something).

The credential verification with `authenticate` is an example of authentication. The checking of groups and permissions is the authorization. The "remember me", while a sort of session, isn't the same as persisting a session for a user on the server side. It's more of a convenience really.

I can see adding a `logout` or something similar but I don't want people thinking that Gatekeeper persists sessions for them. Most frameworks out there will have their own session handling mechanisms.

**Comment by Ser5** [comment]
Looks like I'm already thinking Gatekeeper handles session management. I also was thinking about Gatekeeper as drop-in all-in-one solution for any kind of site, including frameworkless - I have to work with one right now. Now I see that Gatekeeper philosophy doesn't include session management. Anyway, I already created my own simple session management class due to Gatekeeper's strange behaviour described in issue #29. Maybe you should drop some lines into the docs, saying that Gatekeeper doesn't manage sessions - so noone will ask you same question as here. Reading the source code I also have found that Gatekeeper is actually able to kind of "log out" with `RememberMe::deleteToken()`. Seems there is one question left: what to do with the cookie? Thinking in terms of CRUD, if there is a way to create something, then there should be a way to delete it. On other hand if the cookie won't be deleted, browsers delete it after 14 days anyway, leaving no garbage.

As a result I actually don't understand what `RememberMe` should do. If developers have to use other frameworks' session handling mechanisms and guys without frameworks have to code their own session handling, then why `RememberMe` exists? Personally I don't have any problems with `RememberMe` - as I use my own sessions.

**Comment by enygma** [comment]
Yeah, it might be a bit confusing....I could see that. I think since session handling is something that's not really related to auth specifically it's not a part of the Gatekeeper system. The "Remember Me" on the other hand is essentially extending the fact that the user is successfully authenticated past the single point of calling the `Gatekeeper::authenticate` method. That method's only job is to prove the user is who they say they are. The token/cookie is just extending that out to show that they've been verified that way longer than the current session.

The use of the Gatekeeper "remember me" is completely optional, of course - that's why it's disabled by default. I've just seen it coupled with several other auth libraries so figured it could be useful here.

**Comment by enygma** [comment]
Closing this topic out due to inactivity.
