### ISSUE TITLE
Upstream phinx issue with MySQL >= 5.6 prevents setup

### ISSUE THREAD

**Issue by Awnage** [psecio/gatekeeper#39]
As of MySQL 5.6 the default is to enable STRICT_TRANS_TABLE which blows up the phinx log table creation. They are unwilling to add the appropriate patch due to Travis's MySQL version incompatibility. See: https://github.com/robmorgan/phinx/issues/243

To disable STRICT_TRANS_TABLE you need to edit /etc/my.cnf (and /usr/my.cnf on CentOS)

```
sql_mode=NO_ENGINE_SUBSTITUTION
```

I have submitted a new patch (https://github.com/robmorgan/phinx/pull/638) that will hopefully be accepted...

**Comment by enygma** [comment]
Lovely...seems like while Phinx is a good tool, it's getting really far behind on handling user contributed updates (I put in one of my own several months ago and it's yet to be handled).

**Comment by Awnage** [comment]
Hopefully they will accept the patch I just submitted.

**Comment by Awnage** [comment]
Closing as robmorgan/phinx#243 was merged.
