### ISSUE TITLE
can't setup with empty db password

### ISSUE THREAD

**Issue by glensc** [psecio/gatekeeper#42]
```
➔ ./vendor/bin/setup.sh 
--- Executing Gatekeeper setup ----------

> No configuration found, please enter database information:

Hostname [localhost]: 
Database name [gatekeeper]: 
Username: mysql
Password: 
Password cannot be empty!
```

this is annoying restriction, it's my dev machine do i have create separate user to test this project?

**Comment by enygma** [comment]
Having a user without a password is a bad security practice so yeah - you'd need one with a password on it.

**Comment by glensc** [comment]
i know that, but in dev machine i do what i want. why should this package teach me what is good and what is not. if the rest succeeds with the input username/password, it's not this tool business what's the password is or is not. next it will dictate me not to use mysql user named 'root' too because it's bad in some context?

**Comment by enygma** [comment]
The library has no context if you're installing it in a sensitive location or not so it falls back on best practices and requires the password. If you're not happy with it, you're more than welcome to drop in a PR and add a "dev" flag or something to the installer that would remove the requirement.
